### ISSUE TITLE
Request for cropped version of Multi-PIE dataset

### ISSUE THREAD

**Issue by DCore-2046** [danny95333/Siamese-Network-for-Frontal-Face-Synthesis-disentangle-pose-and-light-interference-#1]
Nice work, Could you share the train sets and test sets of cropped version of Multi-PIE at your convenience

**Comment by danny95333** [comment]
Sorry, I don't have the right to do so. It doesn't belong to me.

> Nice work, Could you share the train sets and test sets of cropped version of Multi-PIE at your convenience

Sorry, I don't have the right to do so. It doesn't belong to me.

**Comment by danny95333** [comment]
> Nice work, Could you share the train sets and test sets of cropped version of Multi-PIE at your convenience

Sorry, I don't have the right to do so. It doesn't belong to me.

**Comment by DCore-2046** [comment]
No original dataset, just cropped version is allowed. Thanks

**Comment by DCore-2046** [comment]
No original dataset, just cropped version is allowed. Thanks 
QQ:1375278373
